# Generated by Django 5.2.17 on 2026-09-29 09:18

import apps.audiobooks.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audiobook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(blank=True, upload_to='audiobooks/', validators=[apps.audiobooks.models.validate_audio, django.core.validators.FileExtensionValidator(['mp3', 'm4a', 'wav', 'ogg'])])),
                ('duration', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('audio_file', models.FileField(blank=True, upload_to='chapters/', validators=[apps.audiobooks.models.validate_audio, django.core.validators.FileExtensionValidator(['mp3', 'm4a', 'wav', 'ogg'])])),
                ('duration', models.PositiveIntegerField(default=0)),
                ('order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
