# Generated by Django 5.2.17 on 2026-09-29 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_books', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='books.genre'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['genre', '-created_at'], name='books_book_genre_i_744beb_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['-rating'], name='books_book_rating_e5a7e2_idx'),
        ),
    ]
