# Generated by Django 5.2.17 on 2026-09-29 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0002_initial'),
        ('interactions', '0002_initial'),
        ('reels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='save',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='books.book'),
        ),
        migrations.AddField(
            model_name='save',
            name='reel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='reels.reel'),
        ),
        migrations.AddField(
            model_name='save',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(condition=models.Q(('reel__isnull', False)), fields=('user', 'reel'), name='unique_reel_like'),
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(condition=models.Q(('book__isnull', False)), fields=('user', 'book'), name='unique_book_like'),
        ),
        migrations.AddConstraint(
            model_name='save',
            constraint=models.UniqueConstraint(condition=models.Q(('reel__isnull', False)), fields=('user', 'reel'), name='unique_reel_save'),
        ),
        migrations.AddConstraint(
            model_name='save',
            constraint=models.UniqueConstraint(condition=models.Q(('book__isnull', False)), fields=('user', 'book'), name='unique_book_save'),
        ),
    ]
