# Generated by Django 5.2.17 on 2026-09-29 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comments', '0001_initial'),
        ('reels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='reels.reel'),
        ),
    ]
